
services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
      - "3307:3306"
    networks:
      - app-network
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: carsharingapp
    container_name: carsharingapp
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
      - "8087:8080"
    networks:
      - app-network
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQLDB_DATABASE",
               "spring.datasource.username" : "$MYSQLDB_USER",
               "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
               "jwt.expiration" : "$JWT_EXPIRATION_TIME",
               "jwt.secret" : "$JWT_SECRET",
               "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"
              }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
networks:
  app-network:
    driver: bridge
